# Generated by Django 6.0.5 on 2026-05-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Promo.'),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='preco_promocional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
