# Generated by Django 6.0.5 on 2026-05-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao_curta',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao_longa',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
